# Python Basic operations

In [1]:
class Disease:
  def __init__(self, disease = 'Depression'):
    self.type = disease
    
  def getName(self):
    print("Mental Health Diseases: {0}".format(self.type))

d1 = Disease('Social Anxiety Disorder')
d1.getName()

Mental Health Diseases: Social Anxiety Disorder


In [2]:
# Try Catch Block
# The try block will generate a NameError, because x is not defined:

try:
  print(y)
except NameError:
  print("Well, the variable y is not defined")
except:
  print("OMG, Something else went wrong")


Well, the variable y is not defined


In [3]:

try:
 Value = int(input("Type a number between 1 and 10:"))
except ValueError:
  print("You must type a number between 1 and 10!")
else:
  if (Value > 0) and (Value <= 10):
      print("You typed: ", Value)
  else:
      print("The value you typed is incorrect!")


You typed:  9


# Numpy Array Basics

In [4]:
# importing numpy
import numpy as np

# Defining 1D array
my1DArray = np.array([1, 8, 27, 64])
print(my1DArray)

# Defining and printing 2D array
my2DArray = np.array([[1, 2, 3, 4], [2, 4, 9, 16], [4, 8, 18, 32]])
print(my2DArray)

#Defining and printing 3D array
my3Darray = np.array([[[ 1, 2 , 3 , 4],[ 5 , 6 , 7  ,8]], [[ 1,  2,  3,  4],[ 9, 10, 11, 12]]])
print(my3Darray)



[ 1  8 27 64]
[[ 1  2  3  4]
 [ 2  4  9 16]
 [ 4  8 18 32]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 1  2  3  4]
  [ 9 10 11 12]]]


In [5]:
# Print out memory address
print(my2DArray.data)

# Print the shape of array
print(my2DArray.shape)

# Print out the data type of the array
print(my2DArray.dtype)

"""
Print the stride of the array.
"""
print(my2DArray.strides)

(3, 4)
int32
(16, 4)


# Array using numpy built-in functions

In [6]:
# Array of ones
ones = np.ones((3,4))
print(ones)

# Array of zeros
zeros = np.zeros((2,3,4),dtype=np.int16)
print(zeros)

# Array with random values
np.random.random((2,2))

# Empty array
emptyArray = np.empty((3,2))
print(emptyArray)

# Full array
fullArray = np.full((2,2),7)
print(fullArray)

# Array of evenly-spaced values
evenSpacedArray = np.arange(10,25,5)
print(evenSpacedArray)

# Array of evenly-spaced values
evenSpacedArray2 = np.linspace(0,2,9)
print(evenSpacedArray2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[7 7]
 [7 7]]
[10 15 20]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


# Numpy array and file operations

In [7]:
# Save a numpy array into file
x = np.arange(0.0,50.0,1.0)
np.savetxt('data.out', x, delimiter=',')

# Loading numpy array from text
z = np.loadtxt('data.out', unpack=True)
print(z)

# Loading numpy array using genfromtxt method
my_array2 = np.genfromtxt('data.out',
                      skip_header=1,
                      filling_values=-999)
print(my_array2)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49.]


# Inspecting numpy arrays


In [8]:
# Print the number of `my2DArray`'s dimensions
print(my2DArray.ndim)

# Print the number of `my2DArray`'s elements
print(my2DArray.size)

# Print information about `my2DArray`'s memory layout
print(my2DArray.flags)

# Print the length of one array element in bytes
print(my2DArray.itemsize)

# Print the total consumed bytes by `my2DArray`'s elements
print(my2DArray.nbytes)

2
12
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

4
48


# Broadcasting in NumPy
Broadcasting is a mechanism that permits `NumPy` to operate with arrays of different shapes when performing arithmetic operations. 

In [9]:
# Rule 1: Two dimensions are operatable if they are equal
# Create an array of two dimension
A =np.ones((6, 8))

# Shape of A
print(A.shape)

# Create another array
B = np.random.random((6,8))

# Shape of B
print(B.shape)

# Sum of A and B, here the shape of both the matrix is same.
print(A + B)

(6, 8)
(6, 8)
[[1.86289601 1.23668162 1.33060521 1.38682421 1.03066582 1.56720898
  1.90205832 1.39197407]
 [1.5859597  1.64457251 1.59909609 1.27169491 1.41839131 1.3399213
  1.12941013 1.03447244]
 [1.05455241 1.61889095 1.19369572 1.88704496 1.1772413  1.57232648
  1.44260481 1.27538183]
 [1.77673202 1.16109795 1.96493895 1.8371632  1.89341184 1.29595306
  1.55246999 1.75239764]
 [1.93195883 1.10612401 1.81148644 1.77853932 1.94262209 1.55123634
  1.99795945 1.29331188]
 [1.43779039 1.2551898  1.10990184 1.31275537 1.81184724 1.80178623
  1.96521838 1.73833745]]


In [10]:
# Rule 2: Two dimensions are also comptable when one of them is 1
# Initialize `x`
x = np.ones((3,4))
print(x)

# Check shape of `x`
print(x.shape)

# Initialize `y`
y = np.arange(4)
print(y)

# Check shape of `y`
print(y.shape)

# Subtract `x` and `y`
x - y 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)
[0 1 2 3]
(4,)


array([[ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.],
       [ 1.,  0., -1., -2.]])

In [11]:
# Rule 3: Arrays can be broadcasted together if they are compatible in all dimensions

x = np.ones((6,8))
y = np.random.random((10, 1, 8))
print(x + y)


[[[1.63697632 1.864261   1.5910648  1.05646408 1.45962819 1.97853759
   1.20013973 1.35509892]
  [1.63697632 1.864261   1.5910648  1.05646408 1.45962819 1.97853759
   1.20013973 1.35509892]
  [1.63697632 1.864261   1.5910648  1.05646408 1.45962819 1.97853759
   1.20013973 1.35509892]
  [1.63697632 1.864261   1.5910648  1.05646408 1.45962819 1.97853759
   1.20013973 1.35509892]
  [1.63697632 1.864261   1.5910648  1.05646408 1.45962819 1.97853759
   1.20013973 1.35509892]
  [1.63697632 1.864261   1.5910648  1.05646408 1.45962819 1.97853759
   1.20013973 1.35509892]]

 [[1.26482178 1.58498274 1.55322038 1.8855716  1.0225211  1.37173394
   1.6148223  1.47944079]
  [1.26482178 1.58498274 1.55322038 1.8855716  1.0225211  1.37173394
   1.6148223  1.47944079]
  [1.26482178 1.58498274 1.55322038 1.8855716  1.0225211  1.37173394
   1.6148223  1.47944079]
  [1.26482178 1.58498274 1.55322038 1.8855716  1.0225211  1.37173394
   1.6148223  1.47944079]
  [1.26482178 1.58498274 1.55322038 1.8855716  1

'\nThe dimensions of x(6,8) and y(10,1,8) are diffrent. However, it is possible \nto add them. Why is that? Also, change y(10,2,8) or y(10,1,4) it will \ngive ValueError. Can you find out why?\n'

# Numpy and mathematics at work

In [12]:
# Basica operations (+, -, *, /, %)
x = np.array([[1, 2, 3], [2, 3, 4]])
y = np.array([[1, 4, 9], [2, 3, -2]])

# Add two array
add = np.add(x, y)
print(add)

# Subtract two array
sub = np.subtract(x, y)
print(sub)

# Multipley two array
mul = np.multiply(x, y)
print(mul)

# Divide x, y
div = np.divide(x,y)
print(div)

# Calculated the remainder of x and y
rem = np.remainder(x, y)
print(rem)


[[ 2  6 12]
 [ 4  6  2]]
[[ 0 -2 -6]
 [ 0  0  6]]
[[ 1  8 27]
 [ 4  9 -8]]
[[ 1.          0.5         0.33333333]
 [ 1.          1.         -2.        ]]
[[0 2 3]
 [0 0 0]]


# Subset, Slice, And Index Arrays

In [13]:
x = np.array([10, 20, 30, 40, 50])

# Select items at index 0 and 1
print(x[0:2])

# Select item at row 0 and 1 and column 1 from 2D array
y = np.array([[ 1,  2,  3,  4], [ 9, 10, 11 ,12]])
print(y[0:2, 1])

# Specifying conditions
biggerThan2 = (y >= 2)
print(y[biggerThan2])

[10 20]
[ 2 10]
[ 2  3  4  9 10 11 12]


In [14]:
# Importing pandas
import pandas as pd

# Can you set default parameters in Pandas?


In [15]:
print("Pandas Version:", pd.__version__)

pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)


Pandas Version: 1.5.3


# Data strcutre of pandas


*   Series
*   DataFrames




In [16]:
series = pd.Series([2, 3, 7, 11, 13, 17, 19, 23])
print(series)

# Creating dataframe from Dictionary
dict_df = [{'A': 'Apple', 'B': 'Ball'},{'A': 'Aeroplane', 'B': 'Bat', 'C': 'Cat'}]
dict_df = pd.DataFrame(dict_df)
print(dict_df)
  
# Creating dataframe from Series
series_df = pd.DataFrame({
    'A': range(1, 5),
    'B': pd.Timestamp('20190526'),
    'C': pd.Series(5, index=list(range(4)), dtype='float64'),
    'D': np.array([3] * 4, dtype='int64'),
    'E': pd.Categorical(["Depression", "Social Anxiety", "Bipolar Disorder", "Eating Disorder"]),
    'F': 'Mental health',
    'G': 'is challenging'
})
print(series_df)

# Creating a dataframe from ndarrays
sdf = {
    'County':['Østfold', 'Hordaland', 'Oslo', 'Hedmark', 'Oppland', 'Buskerud'],
    'ISO-Code':[1,2,3,4,5,6],
    'Area': [4180.69, 4917.94, 454.07, 27397.76, 25192.10, 14910.94],
    'Administrative centre': ["Sarpsborg", "Oslo", "City of Oslo", "Hamar", "Lillehammer", "Drammen"]
    }
sdf = pd.DataFrame(sdf)
print(sdf)

0     2
1     3
2     7
3    11
4    13
5    17
6    19
7    23
dtype: int64
           A     B    C
0      Apple  Ball  NaN
1  Aeroplane   Bat  Cat
   A          B    C  D                 E              F               G
0  1 2019-05-26  5.0  3        Depression  Mental health  is challenging
1  2 2019-05-26  5.0  3    Social Anxiety  Mental health  is challenging
2  3 2019-05-26  5.0  3  Bipolar Disorder  Mental health  is challenging
3  4 2019-05-26  5.0  3   Eating Disorder  Mental health  is challenging
      County  ISO-Code      Area Administrative centre
0    Østfold         1   4180.69             Sarpsborg
1  Hordaland         2   4917.94                  Oslo
2       Oslo         3    454.07          City of Oslo
3    Hedmark         4  27397.76                 Hamar
4    Oppland         5  25192.10           Lillehammer
5   Buskerud         6  14910.94               Drammen


# Loading a dataset into Pandas DataFrame



In [17]:
import pandas as pd
columns = ['age', 'workclass', 'fnlwgt', 'education', 'education_num',
    'marital_status', 'occupation', 'relationship', 'ethnicity', 'gender','capital_gain','capital_loss','hours_per_week','country_of_origin','income']
df = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',names=columns)
df.head(10)

age          workclass  fnlwgt   education  education_num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   
5   37            Private  284582     Masters             14   
6   49            Private  160187         9th              5   
7   52   Self-emp-not-inc  209642     HS-grad              9   
8   31            Private   45781     Masters             14   
9   42            Private  159449   Bachelors             13   

           marital_status          occupation    relationship ethnicity  \
0           Never-married        Adm-clerical   Not-in-family     White   
1      Married-civ-spouse     Exec-managerial         Husband     White   
2                Divorced   Handlers-cleaners   Not-in-family     White   
3      Married-civ-spouse   Handlers-cleaners         Husband     Black   
4      Married-civ-spouse      Prof-specialty            Wife     Black   
5      Married-civ-spouse     Exec-managerial            Wife     White   
6   Married-spouse-absent       Other-service   Not-in-family     Black   
7      Married-civ-spouse     Exec-managerial         Husband     White   
8           Never-married      Prof-specialty   Not-in-family     White   
9      Married-civ-spouse     Exec-managerial         Husband     White   

    gender  capital_gain  capital_loss  hours_per_week country_of_origin  \
0     Male          2174             0              40     United-States   
1     Male             0             0              13     United-States   
2     Male             0             0              40     United-States   
3     Male             0             0              40     United-States   
4   Female             0             0              40              Cuba   
5   Female             0             0              40     United-States   
6   Female             0             0              16           Jamaica   
7     Male             0             0              45     United-States   
8   Female         14084             0              50     United-States   
9     Male          5178             0              40     United-States   

   income  
0   <=50K  
1   <=50K  
2   <=50K  
3   <=50K  
4   <=50K  
5   <=50K  
6   <=50K  
7    >50K  
8    >50K  
9    >50K

In [18]:
# Displays the rows, columns, data types and memory used by the dataframe
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   age                32561 non-null  int64 
 1   workclass          32561 non-null  object
 2   fnlwgt             32561 non-null  int64 
 3   education          32561 non-null  object
 4   education_num      32561 non-null  int64 
 5   marital_status     32561 non-null  object
 6   occupation         32561 non-null  object
 7   relationship       32561 non-null  object
 8   ethnicity          32561 non-null  object
 9   gender             32561 non-null  object
 10  capital_gain       32561 non-null  int64 
 11  capital_loss       32561 non-null  int64 
 12  hours_per_week     32561 non-null  int64 
 13  country_of_origin  32561 non-null  object
 14  income             32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [19]:
# Displays the no of data points and columns in the dataframe
df.shape

(32561, 15)

In [20]:
# Display all columns of the dataframe
df.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'ethnicity', 'gender',
       'capital_gain', 'capital_loss', 'hours_per_week', 'country_of_origin',
       'income'],
      dtype='object')

In [21]:
# Displays summary statistics for each numerical column in the dataframe
df.describe()

age        fnlwgt  education_num  capital_gain  capital_loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours_per_week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

# Selecting rows and columns in the dataframe


In [22]:
# Selects a row
df.iloc[10] 

# Selects 10 rows             
df.iloc[0:10]

# Selects a range of rows           
df.iloc[10:15]            

 # Selects the last 2 rows
df.iloc[-2:]  

# Selects every other row in columns 3-5
df.iloc[::2, 3:5].head() 

education  education_num
0   Bachelors             13
2     HS-grad              9
4   Bachelors             13
6         9th              5
8     Masters             14

In [23]:
import pandas as pd
import numpy as np

np.random.seed(24)
df = pd.DataFrame({'F': np.linspace(1, 10, 10)})
df = pd.concat([df, pd.DataFrame(np.random.randn(10, 5), columns=list('EDCBA'))],
               axis=1)
df.iloc[0, 2] = np.nan
df

F         E         D         C         B         A
0   1.0  1.329212       NaN -0.316280 -0.990810 -1.070816
1   2.0 -1.438713  0.564417  0.295722 -1.626404  0.219565
2   3.0  0.678805  1.889273  0.961538  0.104011 -0.481165
3   4.0  0.850229  1.453425  1.057737  0.165562  0.515018
4   5.0 -1.336936  0.562861  1.392855 -0.063328  0.121668
5   6.0  1.207603 -0.002040  1.627796  0.354493  1.037528
6   7.0 -0.385684  0.519818  1.686583 -1.325963  1.428984
7   8.0 -2.089354 -0.129820  0.631523 -0.586538  0.290720
8   9.0  1.264103  0.290035 -1.970288  0.803906  1.030550
9  10.0  0.118098 -0.021853  0.046841 -1.628753 -0.392361

In [24]:
# Define a function that should color the values that are less than 0 
def colorNegativeValueToRed(value):
  if value < 0:
    color = 'red'
  elif value > 0:
    color = 'black'
  else:
    color = 'green'

  return 'color: %s' % color

In [25]:
s = df.style.applymap(colorNegativeValueToRed, subset=['A','B','C','D','E'])
s

In [26]:
# Let us hightlight max value in the column with green background and min value with orange background
def highlightMax(s):
    isMax = s == s.max()
    return ['background-color: orange' if v else '' for v in isMax]

def highlightMin(s):
    isMin = s == s.min()
    return ['background-color: green' if v else '' for v in isMin]

In [27]:
df.style.apply(highlightMax).apply(highlightMin).highlight_null(null_color='red')


C:\Users\Mebarek\AppData\Local\Temp\ipykernel_10920\2115311564.py:1: FutureWarning: `null_color` is deprecated: use `color` instead
  df.style.apply(highlightMax).apply(highlightMin).highlight_null(null_color='red')


In [28]:
import seaborn as sns

cm = sns.light_palette("pink", as_cmap=True)

s = df.style.background_gradient(cmap=cm)
s

In [29]:
class Disease:
  def __init__(self, disease = 'Depression'):
    self.type = disease
    
  def getName(self):
    print("Mental Health Diseases: {0}".format(self.type))

d1 = Disease('Social Anxiety Disorder')
d1.getName()

Mental Health Diseases: Social Anxiety Disorder


In [30]:
try:
  Value = int(input("Type a number between 1 and 10:"))
except ValueError:
   print("You must type a number between 1 and 10!")
else:
   if (Value > 0) and (Value <= 10):
       print("You typed: ", Value)
   else:
       print("The value you typed is incorrect!")

You typed:  5
